version: '3'

services: 
  db:
    container_name: db
    build: ./mysql
    volumes: 
      - ./dbdata:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      
  app:
    container_name: app
    build: ./node
    entrypoint: dockerize -wait tcp://db:3306 node index.js
    volumes: 
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - db

  nginx: 
    container_name: nginx
    build: ./nginx
    restart: always
    entrypoint: dockerize -wait http://app:3000 -timeout 120s /docker-entrypoint.sh nginx -g 'daemon off;'
    ports: 
      - 8080:80
    depends_on: 
      - app